name: iptv优质源

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest
    env:
     TZ: Asia/Shanghai

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖（合并冗余步骤）
        run: |
          sudo apt update -y && sudo apt install -y ffmpeg
          pip install --upgrade pip
          pip install selenium requests futures eventlet
        shell: bash

      - name: tools
        run: | 
          python ./tools/iptv.py
        shell: bash

      - name: move
        run: |
          pwd 
          cd output/
          \cp ./ipv4_result.txt ../live.txt
          cd ../
        shell: bash
          
      - name: 提交更改
        run: |
          git config user.email "zhoujck@live.com"
          git config user.name "zhoujck" 
          git add .
          git commit -m "action: `date`"
          git push -f
     
